# Generated by Django 4.2.5 on 2023-09-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_settings_contact_alter_settings_aboutus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
