# Generated by Django 4.2.5 on 2023-09-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='orders',
            new_name='order',
        ),
    ]
