# Generated by Django 4.2.5 on 2023-09-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slug1',
        ),
    ]
