# Generated by Django 4.2.5 on 2023-09-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_rename_slug_product_slug1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug1',
            new_name='slug',
        ),
    ]
